# Logging 설정
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG  # Spring Web 관련 모든 로그를 DEBUG 수준으로 설정
    your.package.name: DEBUG  # 특정 패키지에 대한 로그 레벨을 DEBUG로 설정
    org.hibernate.SQL: DEBUG  # Hibernate SQL 쿼리 로그를 DEBUG 수준으로 설정
  file:
    path: /logs/app.log  # 로그 파일 경로 설정 (optional)
    max-size: 10MB       # 최대 파일 크기 설정
    max-history: 30      # 로그 파일 보관 기간

spring:

  devtools:
    livereload:
      enabled: true

# #=============jmx 추가
#   jmx:
#     enabled: true
#     default-domain: your.application.domain
# #===============================
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://34.64.236.95:5432/meta_db
    #원본 url: jdbc:postgresql://10.52.208.5:5432/meta_db
    # url: jdbc:postgresql://db:5432/meta_db
    url: jdbc:postgresql://192.168.240.119:5432/meta_db
    username: meta_adm
    password: QweR12#$34
  
  data:
    redis:
#      host: localhost
      host: ct_redis
      port: 6379
#      password: tysredis!23


  # VO location
  # mybatis.type-aliases-package: com.example.web.vo
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
      
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false    

# XML location
mybatis:
  mapper-locations: classpath:mappers/**/*.xml

  http:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

# ======== 도커 배포할때는 해제하고 자바에서 테스트할때는 활성화
# Spring Boot Actuator 설정 (요청 추적을 위한 추가 설정)
management:
  endpoints:
    web:
      exposure:
        include: "httptrace"  # httptrace 엔드포인트를 활성화하여 요청 추적
  endpoint:
    httptrace:
      enabled: true  # httptrace 엔드포인트 활성화
# ========================


# Port
server:
  port: 8081
  
  tomcat:
    connection-timeout: -1
  


