version: '3.3'

services:

  redis:
    container_name: redis
    image: redis:latest
    

  dms:
    container_name: DataModelManagementServerFrontEnd
    image: dmsimg
    build:
      context: ./DataModelManagementServer
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "80:8081"

  std:
    container_name: StandardDataServerBackEnd
    image: stdimg
    build:
      context: ./StandardDataServer
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8082:8082"

    
      
